import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="fixed top-0 left-0 right-0 flex justify-end items-center p-8 z-50 font-sans">
          <nav className="text-white flex items-center space-x-6 mr-10">
            <Link href="/" className="hover:text-gray-300 text-2xl text-white transition duration-300 ease-in-out font-semibold">
              HOME
            </Link>
            <Link href="/profile" className="hover:text-gray-300 text-2xl text-white transition duration-300 ease-in-out font-semibold">
              PROFILE
            </Link>
            <Link href="/works" className="hover:text-gray-300 text-2xl text-white transition duration-300 ease-in-out font-semibold">
              WORKS
            </Link>
            <Link href="/blogs" className="hover:text-gray-300 text-2xl text-white transition duration-300 ease-in-out font-semibold">
              BLOGS
            </Link>
          </nav>
        </header>
        {children}
      </body>
    </html>
  )
}
