import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import './globals.css'
import { IoFootball } from "react-icons/io5";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="text-gray-600 body-font absolute z-50">
          <div className="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
            <Link href="/" className="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0">
              <IoFootball className="text-4xl text-blue-300" />
              <span className="ml-3 text-2xl text-white">MINE BLOG</span>
            </Link>
            <nav className="md:mr-auto md:ml-6 md:py-1 md:pl-4 md:border-l md:border-gray-400	flex flex-wrap items-center text-base justify-center">
              <Link href="/profile" className="mr-5 hover:text-gray-300 text-xl text-white transition duration-300 ease-in-out font-medium">PROFILE</Link>
              <Link href="/works" className="mr-5 hover:text-gray-300 text-xl text-white transition duration-300 ease-in-out font-medium">WORKS</Link>
              <Link href="/blogs" className="mr-5 hover:text-gray-300 text-xl text-white transition duration-300 ease-in-out font-medium">BLOGS</Link>
            </nav>
          </div>
        </header>
        {children}
      </body>
    </html>
  )
}
